"""REST API routes for Veritas AI — Antigravity Engine integration.

Key design:
- Pipeline singleton lives in `request.app.state.pipeline` (init'd via lifespan).
- /query and /verify-news use the JSON path (pipeline.run).
- /stream uses StreamingResponse + SSE (pipeline.stream_run) for <100ms TTFT.
"""
import asyncio
import logging
import time
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse

from app.core.config import settings
from app.core.cache import cache

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1")


# ---- Pipeline accessor ----

def _get_pipeline(request: Request):
    """Retrieve the singleton FridayPipeline from app.state."""
    pipeline = getattr(request.app.state, "pipeline", None)
    if pipeline is None:
        raise HTTPException(
            status_code=503,
            detail="Pipeline not initialized. Server is still starting up.",
        )
    return pipeline


# ---- Auth Helpers ----

def _require_api_key(request: Request) -> str:
    """Extract and validate API key from request headers."""
    api_key = request.headers.get("X-API-KEY")
    if not api_key:
        raise HTTPException(status_code=401, detail="API key required")

    from core.security import validate_api_key
    validate_api_key(api_key)
    return api_key


def _get_owner_email(api_key: str, request: Request) -> str:
    """Resolve owner email from API key, falling back to 'public'."""
    try:
        from core.security import get_current_user
        user = get_current_user(api_key, request)
        return user.get("owner", "public")
    except Exception:
        return "public"


# ---- Query Resolution ----

async def _resolve_query(request: Request, query: str, deep: bool = False, owner_email: str = "public") -> dict:
    """Run query through the singleton pipeline with caching."""
    # Check cache first
    cached = await cache.get(query)
    if cached is not None:
        cached["_cached"] = True
        return cached

    start = time.monotonic()
    pipeline = _get_pipeline(request)

    try:
        response = await pipeline.run(query)
    except Exception as e:
        logger.error(f"Pipeline error: {e}", exc_info=True)
        response = {"response": str(e), "error": True}

    response["latency_ms"] = round((time.monotonic() - start) * 1000, 1)

    # Cache result
    await cache.set(query, response)

    # Log to history (non-blocking)
    try:
        from core.history_store import log_query_result
        from models.schemas import QueryResponse

        payload = QueryResponse(
            response=response.get("response", ""),
            truth_score=response.get("truth_score"),
            sources=response.get("context_used", []),
        )
        asyncio.create_task(asyncio.to_thread(log_query_result, payload, owner_email))
    except Exception:
        pass

    return response


# ---- Endpoints ----

@router.get("/health")
async def health():
    """Health check endpoint."""
    cache_stats = cache.get_stats()
    return {
        "status": "healthy",
        "version": "2.0.0",
        "cache": {
            "redis_available": cache_stats.get("redis_available", False),
            "hit_rate": round(cache_stats.get("hit_rate", 0), 4),
        },
    }


@router.post("/query")
async def query_endpoint(request: Request):
    """Direct query endpoint (no auth required). Returns complete JSON."""
    body = await request.json()
    query = body.get("query", "").strip()
    deep = body.get("deep", False)

    if not query:
        raise HTTPException(status_code=400, detail="Query is required")

    response = await _resolve_query(request, query, deep=deep)
    return response


@router.post("/verify-news")
async def verify_news(request: Request):
    """Public API for news verification (auth required)."""
    api_key = _require_api_key(request)
    owner_email = _get_owner_email(api_key, request)

    body = await request.json()
    query = body.get("claim", body.get("query", "")).strip()
    deep = body.get("deep", False)

    if not query:
        raise HTTPException(status_code=400, detail="Claim/query is required")

    response = await _resolve_query(request, query, deep=deep, owner_email=owner_email)
    return response


@router.post("/stream")
async def stream_query(request: Request):
    """
    Streaming query endpoint — Server-Sent Events.

    Returns tokens as they are generated by Ollama, achieving <100ms
    time-to-first-token. Truth Score and Hallucination Firewall results
    are appended as final SSE events after the LLM finishes.

    SSE event types:
      - meta:        {tier, model}
      - token:       {t: "..."}
      - truth_score: {truth_score: 0.85, breakdown: {...}}
      - done:        {response_length: 142}
    """
    body = await request.json()
    query = body.get("query", "").strip()

    if not query:
        raise HTTPException(status_code=400, detail="Query is required")

    pipeline = _get_pipeline(request)

    return StreamingResponse(
        pipeline.stream_run(query, voice_mode=bool(body.get("voice_mode", False))),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )


@router.post("/voice/stream")
async def voice_stream_endpoint(request: Request):
    """
    Returns an audio/wav stream compatible with the existing Next.js frontend.
    TTFA < 200ms.
    """
    body = await request.json()
    text = body.get("text", "").strip()
    
    if not text:
        raise HTTPException(status_code=400, detail="Text is required for TTS")

    from app.voice.tts_service import tts_service
    
    return StreamingResponse(
        tts_service.stream_audio(text),
        media_type="audio/wav"
    )


@router.post("/stream-analysis")
async def stream_analysis(request: Request):
    """Get WebSocket stream authorization URL (auth required)."""
    api_key = _require_api_key(request)

    body = await request.json()
    query = body.get("query", "").strip()

    separator = "&" if "?" in settings.PUBLIC_WS_BASE_URL else "?"
    return {
        "status": "stream_authorized",
        "tunnel_socket_uri": f"{settings.PUBLIC_WS_BASE_URL}{separator}session_auth={api_key}",
        "query_linked": query,
    }


@router.get("/history")
async def get_history(request: Request, limit: int = 50):
    """Fetch query history."""
    api_key = request.headers.get("X-API-KEY")
    owner_email = _get_owner_email(api_key, request) if api_key else "public"

    try:
        from core.history_store import fetch_recent_history
        history = await asyncio.to_thread(fetch_recent_history, limit, owner_email)
        return {"history": history, "count": len(history)}
    except Exception as e:
        logger.error(f"History fetch failed: {e}")
        return {"history": [], "count": 0, "error": str(e)}


@router.post("/feedback")
async def submit_feedback(request: Request):
    """Submit user feedback (data collection only).
    
    TODO:
    - dataset builder
    - training pipeline
    """
    try:
        body = await request.json()
        from feedback.feedback_service import UserFeedback, process_and_log_feedback

        api_key = request.headers.get("X-API-KEY")
        owner_email = _get_owner_email(api_key, request) if api_key else "public"

        feedback = UserFeedback(**body)
        result = await asyncio.to_thread(process_and_log_feedback, feedback, owner_email)
        return {"status": "received", "message": "Feedback recorded", "result": result}
    except Exception as e:
        logger.error(f"Feedback submission failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/trigger-network-effect")
async def trigger_network_effect(request: Request):
    """Trigger dataset aggregation (auth required)."""
    _require_api_key(request)

    try:
        from feedback.network_effect_builder import extract_and_build_dataset
        result = await asyncio.to_thread(extract_and_build_dataset)
        return {
            "status": result.get("status", "success"),
            "message": result.get("message") or result.get("output_target"),
            "entries_parsed": result.get("entries_parsed", 0),
        }
    except Exception as e:
        logger.error(f"Network effect trigger failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/alerts")
async def get_alerts(request: Request):
    """Fetch active alerts (auth required)."""
    _require_api_key(request)

    try:
        from core.alert_engine import get_recent_alerts
        alerts = get_recent_alerts()
        return {"alerts": alerts}
    except Exception as e:
        logger.error(f"Alerts fetch failed: {e}")
        return {"alerts": [], "error": str(e)}


@router.get("/predictive-trends")
async def get_trends(request: Request):
    """Fetch predictive trends (auth required)."""
    _require_api_key(request)

    try:
        from core.predictive_engine import predictive_engine
        trends = predictive_engine.generate_horizon_predictions()
        return {"trends": trends}
    except Exception as e:
        logger.error(f"Trends fetch failed: {e}")
        return {"trends": [], "error": str(e)}


@router.post("/voice/set")
async def set_voice_profile(request: Request):
    """Set TTS voice profile."""
    body = await request.json()
    profile = body.get("voice", "friday")
    from app.voice.tts import set_voice
    set_voice(profile)
    return {"status": "ok", "voice": profile}


@router.get("/metrics")
async def get_metrics():
    """Get system metrics."""
    cache_stats = cache.get_stats()
    return {
        "cache": cache_stats,
        "version": "2.0.0",
    }


@router.post("/cache/clear")
async def clear_cache():
    """Clear all caches."""
    await cache.clear()
    return {"status": "cleared"}
